import "./globals.css";
import mysql from 'mysql2/promise';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const pool = mysql.createPool({
  host: process.env.LIT_STAR_DB_HOST_URL,
  user: process.env.LIT_STAR_DB_USER,
  password: process.env.LIT_STAR_DB_PASSWORD,
  database: process.env.LIT_STAR_DB_NAME,
  waitForConnections: true,
  connectionLimit: 50,
});
export async function Root_Movies_DB(query, params = []) {
  try {
    const [results] = await pool.query(query, params);
    return results;
  } catch (error) {
    throw error;
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
